In [1]:
import pandas as pd

df = pd.read_csv("../data/house_price.csv")

df.head()

   area_sqft  bedrooms  bathrooms  parking     location    price
0        850         2          1        1  Bhubaneswar  3200000
1       1000         2          2        1  Bhubaneswar  4000000
2       1200         3          2        1  Bhubaneswar  5200000
3       1500         3          2        2  Bhubaneswar  6800000
4       1800         4          3        2  Bhubaneswar  8500000

In [2]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (20, 6)

In [3]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['area_sqft', 'bedrooms', 'bathrooms', 'parking', 'location', 'price'], dtype='str')

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
area_sqft    0
bedrooms     0
bathrooms    0
parking      0
location     0
price        0
dtype: int64

In [5]:
df.describe()

         area_sqft   bedrooms  bathrooms    parking         price
count    20.000000  20.000000  20.000000  20.000000  2.000000e+01
mean   1307.500000   2.800000   2.000000   1.400000  5.015000e+06
std     387.051948   0.767772   0.648886   0.502625  1.822166e+06
min     750.000000   2.000000   1.000000   1.000000  2.500000e+06
25%    1000.000000   2.000000   2.000000   1.000000  3.475000e+06
50%    1250.000000   3.000000   2.000000   1.000000  4.650000e+06
75%    1562.500000   3.000000   2.000000   2.000000  6.350000e+06
max    2000.000000   4.000000   3.000000   2.000000  8.500000e+06

In [6]:
print("Data Types:")
print(df.dtypes)

Data Types:
area_sqft    int64
bedrooms     int64
bathrooms    int64
parking      int64
location       str
price        int64
dtype: object

In [7]:
print("Locations in the dataset:")
print(df["location"].unique())

Locations in the dataset:
<StringArray>
['Bhubaneswar', 'Cuttack', 'Puri', 'Berhampur']
Length: 4, dtype: str

In [8]:
print("Number of houses in each location:")
print(df["location"].value_counts())

Number of houses in each location:
location
Bhubaneswar    5
Cuttack        5
Puri           5
Berhampur      5
Name: count, dtype: int64

In [9]:
print("Average house price by location:")
print(df.groupby("location")["price"].mean())

Average house price by location:
location
Berhampur      4540000.0
Bhubaneswar    5540000.0
Cuttack        5180000.0
Puri           4800000.0
Name: price, dtype: float64

In [10]:
df["price_per_sqft"] = df["price"] / df["area_sqft"]

print("Price per square foot:")
print(df[["location", "area_sqft", "price", "price_per_sqft"]])

Price per square foot:
       location  area_sqft    price  price_per_sqft
0   Bhubaneswar        850  3200000     3764.705882
1   Bhubaneswar       1000  4000000     4000.000000
2   Bhubaneswar       1200  5200000     4333.333333
3   Bhubaneswar       1500  6800000     4533.333333
4   Bhubaneswar       1800  8500000     4722.222222
5       Cuttack        900  3000000     3333.333333
6       Cuttack       1100  3900000     3545.454545
7       Cuttack       1300  4800000     3692.307692
8       Cuttack       1600  6200000     3875.000000
9       Cuttack       2000  8000000     4000.000000
10         Puri        750  2800000     3733.333333
11         Puri       1000  3500000     3500.000000
12         Puri       1250  4500000     3600.000000
13         Puri       1550  5700000     3677.419355
14         Puri       1900  7500000     3947.368421
15    Berhampur        800  2500000     3125.000000
16    Berhampur       1050  3400000     3238.095238
17    Berhampur       1250  4300000     3440.000000
18    Berhampur       1500  5500000     3666.666667
19    Berhampur       1850  7000000     3783.783784

In [11]:
df.to_csv("../data/cleaned_house_prices.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!